### ISSUE TITLE
Fail to export ability

### ISSUE THREAD

**Issue by sulaimanbale** [xenoscr/atomiccaldera#10]
![image](https://user-images.githubusercontent.com/46603663/65573158-ae14c600-df9c-11e9-8ed6-6d7c8fb3e021.png)

![image](https://user-images.githubusercontent.com/46603663/65584309-45851380-dfb3-11e9-8b64-dc8f83ccb9c7.png)

**Comment by xenoscr** [comment]
Duplicate, please search for solutions before opening issues. ttps://github.com/xenoscr/atomiccaldera/issues/5

**Comment by xenoscr** [comment]
Duplicate
