### ISSUE TITLE
Error importing  techniques

### ISSUE THREAD

**Issue by sedoy107** [xenoscr/atomiccaldera#11]
It seems like the main script app/atomic_caldera.py is trying to walk recursively atomic-red-team(ART) directory in its entirety searching for .yaml files. However the if the ART directory has .yaml that is not a valid technique, the import operation may fail. 

Error message:

DEBUG:atomiccaldera:Processing ~/caldera/plugins/atomiccaldera/atomic-red-team/atomic_red_team/atomic_test_template.yaml
invalid literal for int() with base 10: 'ODO'
invalid literal for int() with base 10: 'ODO'
invalid literal for int() with base 10: 'ODO'
DEBUG:atomiccaldera:Processing ~/caldera/plugins/atomiccaldera/atomic-red-team/atomic_red_team/spec.yaml
ERROR:atomiccaldera:'executor'

In the line 98 of app/atomic_caldera.py there should be either hardcoded condition to skip a file if it is not within atomic-red-team/atomics/ path. Another fix could be having the path to to search within set in the config file.

**Comment by xenoscr** [comment]
The path in the config file should point at the "atomics" folder. This should resolve the issue.
