### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_logger'

### ISSUE THREAD

**Issue by cyber-cyborg999** [xenoscr/atomiccaldera#4]
Hi,

When i tried to install this plugin i got the following error,

Traceback (most recent call last):
  File "server.py", line 109, in <module>
    main(services=data_svc.get_services(), host=cfg['host'], port=cfg['port'], users=cfg['users'])
  File "server.py", line 73, in main
    loop.run_until_complete(init(host, port, services, users))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "server.py", line 65, in init
    await attach_plugins(app, services)
  File "server.py", line 50, in attach_plugins
    await plugin(app, services)
  File "/opt/caldera/plugins/atomiccaldera/hook.py", line 27, in initialize
    ac_data_svc = ACDatabase(CoreDao('ac.db', False), services.get('utility_svc'))
  File "/opt/caldera/plugins/atomiccaldera/app/ac_database.py", line 22, in __init__
    self.log = utility_svc.create_logger('ac_data_svc')
AttributeError: 'NoneType' object has no attribute 'create_logger'

Is there something i am missing ?

Regards,
Sai Santosh

**Comment by xenoscr** [comment]
No, I don't think you are. The MITRE team is still developing Caldera very actively and it appears that they have changed how logging is handled. I will need to take some time to figure out these most recent changes and get the plugin to work again. There are also a number of other changes I plan on making, again, all to keep up with the rapid drastic changes that MITRE is making.

**Comment by xenoscr** [comment]
I have corrected the error setting up logging caused by the upstream changes. Thanks for checking out my project. If you have any suggestions or feedback I am interested in hearing it. I have many plans to improve the project and integrate features that MITRE has added and changed in Caldera.
