### ISSUE TITLE
atomiccaldera: _dump_all()

### ISSUE THREAD

**Issue by Ads5740** [xenoscr/atomiccaldera#5]
Hi, 
Pulled latest Caldera today and this repo.
When trying to export an ability, I get the following error:
ERROR:atomiccaldera:_dump_all() got an unexpected keyword argument 'sort_keys'

**Comment by xenoscr** [comment]
Make sure that you have, at minimum, the version of PyYAML that is listed in the requirements.txt file. Older versions do not support that argument.

Conor

**Comment by twistingjackomo** [comment]
the reason is: caldera needs pyyaml===4.2b1, atomiccaldera pyyaml>=5.1

**Comment by twistingjackomo** [comment]
> Hi,
> Pulled latest Caldera today and this repo.
> When trying to export an ability, I get the following error:
> ERROR:atomiccaldera:_dump_all() got an unexpected keyword argument 'sort_keys'

Workaround: With pip you can switch between the requirements and export them all. After that changing back again. Not clean but it works for me...

**Comment by xenoscr** [comment]
Caldera works with the newer versions of PyYAML without issue. No need to switch back and forth.

**Comment by xenoscr** [comment]
Closing as this seems to be resolved by installing the newer module.
