### ISSUE TITLE
Errors installations

### ISSUE THREAD

**Issue by sulaimanbale11** [xenoscr/atomiccaldera#6]
![Screenshot_20190924_195743_com whatsapp w4b](https://user-images.githubusercontent.com/50750136/65509692-9d654100-df05-11e9-8e87-ba821368e836.jpg)
![IMG-20190924-WA0022](https://user-images.githubusercontent.com/50750136/65509712-a5bd7c00-df05-11e9-8939-2e358fb4e239.jpg)

Error in installation please help 2 images are attached.

**Comment by xenoscr** [comment]
Did you install the required Python libraries using the requirements.txt file in the root directory of atomicaldera? Also, did you use a tab instead of spaces in your configuration file?

**Comment by sulaimanbale11** [comment]
I use tab, so now I'll change to space and try , I've install all the requirements.

**Comment by sulaimanbale11** [comment]
I was able to install stix but canno ininstall stix2

**Comment by xenoscr** [comment]
Interesting, it seems to indicate that it cannot load the stix2 module. Try opening a Python console and try to load it to make sure it works.

**Comment by sulaimanbale11** [comment]
Okay , but how can I load in python console I'm not sure ?

**Comment by sulaimanbale11** [comment]
![IMG-20190924-WA0037](https://user-images.githubusercontent.com/50750136/65516659-f89e3000-df13-11e9-80f0-6e165a8648fb.jpg)
Is it this ?

**Comment by sulaimanbale11** [comment]
O
![IMG-20190924-WA0039](https://user-images.githubusercontent.com/50750136/65518115-5c295d00-df16-11e9-8c4c-262f3c54ed19.jpg)

Is it this ?

**Comment by sulaimanbale11** [comment]
![IMG-20190924-WA0041](https://user-images.githubusercontent.com/50750136/65519230-4157e800-df18-11e9-9500-1f1ee85aab10.jpg)

Please help !!

**Comment by sulaimanbale11** [comment]
![IMG-20190924-WA0042](https://user-images.githubusercontent.com/50750136/65519365-6187a700-df18-11e9-861a-339a4dbd445d.jpg)


Errors

**Comment by xenoscr** [comment]
Have you tried manually installing stix2 with pip? If you are not sure how to do that please consult the manuals and documentation for pip. You will continue to have issues until you are able to properly install the dependencies.

**Comment by sulaimanbale11** [comment]
I tired but it's not working

**Comment by sulaimanbale11** [comment]
Do you have any working virtual machines , do you mind dropping a link?

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65538463-f18a1880-df39-11e9-901f-df2052c8aae4.png)

Which directory to install this 2 ?

**Comment by xenoscr** [comment]
I cannot provide support for your Python issues. To answer the where to clone the required repositories. Anywhere you like. You can configure the paths in the configuration file.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65562700-d4753a00-df79-11e9-8ee8-7e70275e61b8.png)

install stix2 still no module error

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65562764-1aca9900-df7a-11e9-8aec-ffcfa1bae395.png)

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65563175-4c902f80-df7b-11e9-8e84-085f0b54fa69.png)

Managned to fix them, this error is now appearing.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65563315-c45e5a00-df7b-11e9-9206-6081a0e63818.png)

Unable to fix

**Comment by xenoscr** [comment]
I cannot help you with basic Python issues.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65563913-c0333c00-df7d-11e9-956b-b16d3892798c.png)

My error is fixed this is the error now.

**Comment by sulaimanbale** [comment]
> I cannot help you with basic Python issues.

![image](https://user-images.githubusercontent.com/46603663/65563945-dccf7400-df7d-11e9-9c31-dfef2ce5a873.png)

This is directory error,.
