### ISSUE TITLE
Dirctory error

### ISSUE THREAD

**Issue by sulaimanbale** [xenoscr/atomiccaldera#7]
![image](https://user-images.githubusercontent.com/46603663/65564021-1acc9800-df7e-11e9-8250-6ad8f9316952.png)

Please help!!

**Comment by xenoscr** [comment]
Now your trouble is basic Linux shell functionality most likely. Do you by chance have a ~ in front of your path in the configuration file?

**Comment by sulaimanbale** [comment]
yes 

![image](https://user-images.githubusercontent.com/46603663/65564557-e063fa80-df7f-11e9-97cc-ed6809269c81.png)


I remove ~ now it's working.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65564659-21f4a580-df80-11e9-95ad-e0ad345026d5.png)


It's working.
