### ISSUE TITLE
Failed to load abilities

### ISSUE THREAD

**Issue by sulaimanbale** [xenoscr/atomiccaldera#8]
![image](https://user-images.githubusercontent.com/46603663/65564907-f8884980-df80-11e9-8513-a68e65ca38ff.png)

![image](https://user-images.githubusercontent.com/46603663/65564958-1e155300-df81-11e9-8210-8971c7b965ed.png)

Failed to load abilities. Any fix?

**Comment by xenoscr** [comment]
Perhaps you need to start fresh? I just did a completely new download of Caldera, Atomic Red Team, and Atomic Caldera. The import is working fine. The error you are showing did not occur for me. All abilities successfully imported for me.

**Comment by sulaimanbale** [comment]
I restart my ubuntu VM still having the same errors for me.
![image](https://user-images.githubusercontent.com/46603663/65566179-a8ab8180-df84-11e9-8051-88671e617aea.png)

What shall i do now ?

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65566853-a5b19080-df86-11e9-8bd7-517274b4054f.png)

Try it on new virtual machine still receiving same error!!

**Comment by sulaimanbale** [comment]
Hi managed to work, installed caldera using it's requirements txt using pip3.6 again it is working now !!

![Uploading image.png…]()

**Comment by sulaimanbale** [comment]
Hi managed to work, installed caldera using it's requirements txt using pip3.6 again it is working now !!

![image](https://user-images.githubusercontent.com/46603663/65567736-df37cb00-df89-11e9-93e2-ae6ac568f3cf.png)

**Comment by sulaimanbale** [comment]
Abilities still fail to load despite trying!!

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65568744-7a7e6f80-df8d-11e9-9f3b-35b0323c9292.png)

After changing to atomics it managed to work!!
