### ISSUE TITLE
Restart DB

### ISSUE THREAD

**Issue by sulaimanbale** [xenoscr/atomiccaldera#9]
How do i restart db ?

After clicking yes, it will then take some time for the abilities to complete reloading. NOTE: It is necessary to restart Caldera to view the new abilities. At the moment there is no way to force Chain to reload its database from the GUI.

How do i reload ?

**Comment by xenoscr** [comment]
Log out of Caldera, stop it, start it. Perhaps you should start by studying basic computing.
